language: python

dist: focal
sudo: false

python:
  - "3.6"
  - "3.9"

install:
  - pip install --quiet 'pylint<2.5' coveralls

script:
  - coverage run --source pigwig --omit 'pigwig/tests/*' -m unittest -v
  - pylint pigwig

after_success:
  coveralls

notifications:
  email:
    on_success: change
    on_failure: change
